controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute_4
      - Revolute_5
      - Revolute_6
      - Revolute_7
initial:  # Define initial robot poses per group
  - group: arm
    pose: init