arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Revolute_4
    - Revolute_5
    - Revolute_6
    - Revolute_7
  gains:
    Revolute_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1