controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Revolute_4
      - Revolute_5
      - Revolute_6
      - Revolute_7